apiVersion: v1 
kind: Service
metadata:
  name: medrec-service
spec:
  type: NodePort
  ports:
  - port: 7011
  selector:
    app: app-medrec
---
apiVersion: v1
kind: Service
metadata:
  name: medrec-service-lb
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.1.55
  ports:
  - port: 7011
  selector:
    app: app-medrec
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medrec
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-medrec
  template:
    metadata:
      labels:
        app: app-medrec
    spec:
      containers:
      - name: medrec
        image: apmoptimize/12212-medrec
        ports:
        - containerPort: 7011
        envFrom:
            - configMapRef:
                name: rvbd-instrumentation-env
        env:
          - name: RVBD_DSAHOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP                  
        volumeMounts:
        - mountPath: /opt/Panorama
          name: rvbd-files
      volumes:
      - hostPath:
          path: /opt/Panorama
        name: rvbd-files